/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BookResponse {
  archived?: boolean;
  author?: string;
  bookCover?: Array<string>;
  id?: number;
  isbn?: string;
  note?: number;
  owner?: string;
  shareable?: boolean;
  synopsis?: string;
  title?: string;
}
