/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BorrowedBookResponse {
  author?: string;
  isbn?: string;
  returnApproved?: boolean;
  returned?: boolean;
  title?: string;
}
